
# Forest plots of relative risk {#RR-forest}

---
output:
  pdf_document:
    keep_tex: yes
fontfamily: mathpazo
fontsize: 9pt
---

\raggedright

## Overview

__Purpose: __
__Interpretation: __
__Implications: __



```{r setup, include=FALSE}
library(knitr)
#library(tidyverse)
knitr::opts_chunk$set(echo = FALSE, message=FALSE)
source(paste0(here::here(), "/0-config.R"))

d <- readRDS(file=paste0(fig_dir, "/risk-factor/figure-data/all_forest_plot_RR.RDS"))

#Note- need to sort plots by order of outcome variables and age categories I want here


```


<!-- ** [Coming soon] Will fill in with all primary forest plots - right now this page is empty due to the file size/difficuty publishing all the plots ** -->


<!-- Group plots by exposure -->

<!-- ```{r  echo=FALSE, results='asis'} -->

<!--   #  df <- d #%>% filter() -->
<!--   # #Dynamic title -->
<!--   # cat(paste0("#### Outcome: ",df$outcome_variable[1]," Exposure: ", df$intervention_variable[1], " Age: ",  df$agecat[1])) -->

<!-- ``` -->


```{r, echo = FALSE, results='asis'}
i<-1
for(i in 1:4){
#for(i in 1:length(d[[4]])){
  
    cat(paste0("\n#### Outcome: ",d$outcome_variable[1]," Exposure: ", d$intervention_variable[1], " Age: ",  d$agecat[1]),"\n,")
  
  print(d$plot[i][[1]])
}
```


